### ISSUE TITLE
Error in compiling, please help!

### ISSUE THREAD

**Issue by Drakaroft** [zajako/qici_desktop#1]
i get this when i try to write "npm install && npm start"

C:\Users\Andrea_F>cd qici_desktop

C:\Users\Andrea_F\qici_desktop>npm install && npm start
npm ERR! install Couldn't read dependencies
npm ERR! Windows_NT 6.1.7601
npm ERR! argv "F:\Programmi Secondari-Varie\NodeJS\node.exe" "F:\Programmi S
econdari-Varie\NodeJS\node_modules\npm\bin\npm-cli.js" "install"
npm ERR! node v4.5.0
npm ERR! npm  v2.15.9
npm ERR! path C:\Users\Andrea_F\qici_desktop\package.json
npm ERR! code ENOPACKAGEJSON
npm ERR! errno -4058
npm ERR! syscall open

npm ERR! package.json ENOENT: no such file or directory, open 'C:\Users\Andrea_F
\qici_desktop\package.json'
npm ERR! package.json This is most likely not a problem with npm itself.
npm ERR! package.json npm can't find a package.json file in your current directo
ry.

npm ERR! Please include the following file with any support request:
npm ERR!     C:\Users\Andrea_F\qici_desktop\npm-debug.log

**Comment by zajako** [comment]
change to the src directory and try
